### ISSUE TITLE
Mappings not being shown

### ISSUE THREAD

**Issue by Tehnix** [Tehnix/spaceneovim#23]
It seems I'm currently being affected by https://github.com/hecal3/vim-leader-guide/issues/39. 

The workaround currently is to add keys in the style of `let g:lmap.b.C = ['%y *', 'copy-whole-buffer']` instead of the usual way.

I'll make some work on converting all existing layers.

**Comment by Tehnix** [comment]
Better workaround to keep the existing API, is to make the internal functions work under `au VimEnter`.

**Comment by Tehnix** [comment]
The bindings have all been fixed in https://github.com/Tehnix/spaceneovim/tree/refactor, although there still remains a problem where if Nvim is opened directly on a file, and not just in the home screen (i.e. `nvim myFile.hs`), then `vim-leader-guide` reopens after running commands, and resets the cursor to the top of the file.

When this is resolved, everything should be good to go.

**Comment by lowski** [comment]
@Tehnix I've tested it on `refactor` branch (for `spaceneovim` as well as layers) and it still does not show all mapping for me.

**Comment by Tehnix** [comment]
@lowski hmm, are there any specific ones, or is it a lot of them?

**Comment by Tehnix** [comment]
This was resolved with commit ab1414e0899e7ae74e0e80f59903f66f0b0cb5d3.
